### ISSUE TITLE
New version of `pypums` coming might break this

### ISSUE THREAD

**Issue by chekos** [ballet/predict-census-income#48]
Hi! I'm the maintainer of `pypums` and I see you're using it on this repo. I'm not sure if this is expected to be used in the future but just wanted to give y'all a heads up. I'm releasing a new version of `pypums` soon and there are a couple of things that are going to break this part below. 

https://github.com/ballet/predict-census-income/blob/46e5a47ee97b29427eabef4377a02ddbb2e3a415/.bin/split/main.py#L58-L84

Mainly, the `person_or_household` argument for `ACS()` changed to `sample_unit` and `.download_data()` has been renamed to simply `.download()`.

Also, the check you have to see if the data had been previously downloaded won't work because the extracted data will now go to `interim/acs_18/...` instead of `interim/ACS_18/...`. In the new version (`0.1`) `pypums` should be able to detect if the data had been previously downloaded and it won't try to download it again unless you pass the argument `overwrite=True`. 

You can pin your dependency to version `0.0.7` (which is what you're using right now). Version `0.1` is where the breaking changes are introduced.

This seems like a really cool project, thanks for using `pypums`!

**Comment by micahjsmith** [comment]
Thanks for this useful project and for taking the time to notify downstream projects!

We use pypums in a one-off script and only access the 2018 data. Pinned to 0.0.7 in 041d241 which I presume will continue to work. Thanks!
